name: Tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    strategy:
      matrix:
        nvim-versions: ['stable', 'nightly']
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changed
        with:
          filters: |
            lua:
              - 'lua/**'
              - 'tests/**'

      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.nvim-versions }}

      - name: run tests
        if: steps.changed.outputs.lua == 'true'
        run: make test
